Expand BV reasoning to up to 128 bits
uwplse/ruler pull request #75
Opened 2022-10-23 16:34 UTC by VTCAKAVSMoACE

This allows for the use of bv64, bv128. Might be worthwhile to model arbitrarily sized bitvecs in the future using bitvec, but this should cover most reasonable situations.

2022-11-22 04:37 UTC, chandrakananandi requested changes
Hey there, thanks for this PR, this is super helpful. One quick note: we recently did a big refactor and looks like there is a tiny merge conflict. If you resolve it, we will merge this.

Thanks again for contributing!

2022-11-22 16:52 UTC, VTCAKAVSMoACE commented
I would be happy to, but I am uncertain how to test it. The APIs have changed without the docs updating as well, and the CI tests don't appear to work on my system (`cargo` is seemingly invoked incorrectly?).

I have rebased and made a "best effort" guess on how this was intended. Please let me know if it works for you and how to use ruler in the future!

2022-11-23 18:04 UTC, chandrakananandi commented
> I would be happy to, but I am uncertain how to test it. The APIs have changed without the docs updating as well, and the CI tests don't appear to work on my system (`cargo` is seemingly invoked incorrectly?).
> 
> I have rebased and made a "best effort" guess on how this was intended. Please let me know if it works for you and how to use ruler in the future!

Thank you! Indeed the main branch is currently changing a lot but soon will be stable. We are moving away from the iteration based enumeration towards a more workloaded guided approach. We will update the docs shortly.

We will take a look and merge your work.

In the mean time, if you want a stable version of the tool, please use the `oopsla21-aec` branch which corresponds to the artifact for our [paper](https://dl.acm.org/doi/10.1145/3485496).

2022-11-23 18:07 UTC, chandrakananandi approved these changes

2022-11-23 18:07 UTC, merged